# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Academics_Win.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets  # Importing Libraries

import Academics   # Importing Academics.py

from Admissions_Win import Ui_Admissions_Win  # Importing Admissions_Win.py
from Curriculum_Win import Ui_Curriculum_Win  # Importing Curriculum_Win.py
from Classes_Win import Ui_Classes  # Importing Classes_Win.py
from pta_Win import Ui_PTA_C  # Importing pta_Win.py



class Ui_Academics_Win(object):
    def setupUi(self, Academics_Win):
        Academics_Win.setObjectName("Academics_Win")
        Academics_Win.resize(1600, 820)
        Academics_Win.setMinimumSize(QtCore.QSize(1600, 800))
        Academics_Win.setStyleSheet("background-image: url(:/Background/magicpattern-gradient-1690353787077.jpeg);")
        self.gridLayout = QtWidgets.QGridLayout(Academics_Win)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(9, 0, 9, 0)
        self.gridLayout.setSpacing(35)
        self.gridLayout.setObjectName("gridLayout")
        self.Curriculum = QtWidgets.QPushButton(Academics_Win)
        self.Curriculum.setMinimumSize(QtCore.QSize(0, 120))
        self.Curriculum.setStyleSheet("QPushButton{\n"
"background-color: none;\n"
"color:white;\n"
"border-width: 2px;\n"
"font:bold 25px;\n"
"border-radius: 8px;\n"
"padding: 5px;\n"
"border: 2px solid blue;\n"
"border-style: groove;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: white;\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 170, 0);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Curriculum.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Curriculum.setIcon(icon)
        self.Curriculum.setIconSize(QtCore.QSize(37, 37))
        self.Curriculum.setObjectName("Curriculum")
        self.Curriculum.clicked.connect(lambda: self.userButtonresponse('Curriculum'))
        self.Curriculum.clicked.connect(Academics_Win.close)
        self.gridLayout.addWidget(self.Curriculum, 5, 1, 1, 1)
        self.Classes = QtWidgets.QPushButton(Academics_Win)
        self.Classes.setMinimumSize(QtCore.QSize(0, 120))
        self.Classes.setStyleSheet("QPushButton{\n"
"background-color: none;\n"
"color:white;\n"
"border-width: 2px;\n"
"font:bold 25px;\n"
"border-radius: 8px;\n"
"padding: 5px;\n"
"border: 2px solid blue;\n"
"border-style: groove;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: white;\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 170, 0);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/ClassIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Classes.setIcon(icon1)
        self.Classes.setIconSize(QtCore.QSize(35, 40))
        self.Classes.setObjectName("Classes")
        self.Classes.clicked.connect(lambda: self.userButtonresponse('Classes'))
        self.Classes.clicked.connect(Academics_Win.close)
        self.gridLayout.addWidget(self.Classes, 5, 0, 1, 1)
        self.Circular = QtWidgets.QPushButton(Academics_Win)
        self.Circular.setMinimumSize(QtCore.QSize(0, 120))
        self.Circular.setStyleSheet("QPushButton{\n"
"background-color: none;\n"
"color:white;\n"
"border-width: 2px;\n"
"font:bold 25px;\n"
"border-radius: 8px;\n"
"padding: 5px;\n"
"border: 2px solid blue;\n"
"border-style: groove;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: white;\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 170, 0);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Circular_PTA.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Circular.setIcon(icon2)
        self.Circular.setIconSize(QtCore.QSize(40, 40))
        self.Circular.setObjectName("Circular")
        self.Circular.clicked.connect(lambda: self.userButtonresponse('Circulars'))
        self.Circular.clicked.connect(Academics_Win.close)
        self.gridLayout.addWidget(self.Circular, 2, 1, 1, 1)
        self.Academics = QtWidgets.QLabel(Academics_Win)
        self.Academics.setMaximumSize(QtCore.QSize(1600, 110))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Academics.setFont(font)
        self.Academics.setAutoFillBackground(False)
        self.Academics.setStyleSheet("QLabel{\n"
"background: transparent;\n"
"}")
        self.Academics.setScaledContents(True)
        self.Academics.setAlignment(QtCore.Qt.AlignCenter)
        self.Academics.setObjectName("Academics")
        self.gridLayout.addWidget(self.Academics, 0, 0, 1, 2)
        self.Admissions = QtWidgets.QPushButton(Academics_Win)
        self.Admissions.setMinimumSize(QtCore.QSize(0, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Admissions.setFont(font)
        self.Admissions.setStyleSheet("QPushButton{\n"
"background-color: none;\n"
"color:white;\n"
"border-width: 2px;\n"
"font:bold 25px;\n"
"border-radius: 8px;\n"
"padding: 5px;\n"
"border: 2px solid blue;\n"
"border-style: groove;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: white;\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 170, 0);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/admissions_Win_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Admissions.setIcon(icon3)
        self.Admissions.setIconSize(QtCore.QSize(35, 37))
        self.Admissions.setObjectName("Admissions")
        self.Admissions.clicked.connect(lambda: self.userButtonresponse('Admissions'))
        self.Admissions.clicked.connect(Academics_Win.close)
        self.gridLayout.addWidget(self.Admissions, 2, 0, 1, 1)
        self.Home = QtWidgets.QPushButton(Academics_Win)
        self.Home.setMinimumSize(QtCore.QSize(0, 120))
        self.Home.setStyleSheet("QPushButton{\n"
"background-color: none;\n"
"color:white;\n"
"border-width: 2px;\n"
"font:bold 25px;\n"
"border-radius: 8px;\n"
"padding: 5px;\n"
"border: 2px solid blue;\n"
"border-style: groove;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: white;\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 170, 0);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/homeIcon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Home.setIcon(icon4)
        self.Home.setIconSize(QtCore.QSize(30, 30))
        self.Home.setObjectName("Home")
        self.gridLayout.addWidget(self.Home, 7, 0, 1, 2)
        self.Home.clicked.connect(lambda: self.userButtonresponse('Home'))
        self.Home.clicked.connect(Academics_Win.close)
        self.retranslateUi(Academics_Win)
        QtCore.QMetaObject.connectSlotsByName(Academics_Win)

    def retranslateUi(self, Academics_Win):
        _translate = QtCore.QCoreApplication.translate
        Academics_Win.setWindowTitle(_translate("Academics_Win", "Dialog"))
        self.Curriculum.setText(_translate("Academics_Win", " Curriculum"))
        self.Classes.setText(_translate("Academics_Win", " Classes"))
        self.Circular.setText(_translate("Academics_Win", " Circular/ PTA"))
        self.Academics.setText(_translate("Academics_Win", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; color:#ffffff;\">Academics</span></p></body></html>"))
        self.Admissions.setText(_translate("Academics_Win", " Admissions"))
        self.Home.setText(_translate("Academics_Win", " Home"))

    def userButtonresponse(self, button):
        """
        This function prints which button(s) user has clicked and executes
        the necessary functions as required by the user.

        :param button:
        :return:
        """
        if button == 'Admissions':
            from Admissions_Win import Ui_Admissions_Win
            print('Admissions Pressed')
            self.window = QtWidgets.QDialog()
            self.ui = Ui_Admissions_Win()
            self.ui.setupUi(self.window)
            self.window.show()
            print("Admissions Window Opened")
        elif button == 'Classes':
            print('Classes Pressed')
            from Classes_Win import Ui_Classes
            self.window = QtWidgets.QDialog()
            self.ui = Ui_Classes()
            self.ui.setupUi(self.window)
            self.window.show()
        elif button == 'Curriculum':
            from Curriculum_Win import Ui_Curriculum_Win
            print('Curriculum pressed')
            self.window = QtWidgets.QDialog()
            self.ui = Ui_Curriculum_Win()
            self.ui.setupUi(self.window)
            self.window.show()
            print("Curriculum and Book List Window Opened")
        elif button == 'Circulars':
            from pta_Win import Ui_PTA_C
            print('Circulars pressed')
            self.window = QtWidgets.QDialog()
            self.ui = Ui_PTA_C()
            self.ui.setupUi(self.window)
            self.window.show()
        elif button == 'Home':
            print('Home pressed')
            from School_Reception import Ui_MainWindow
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_MainWindow()
            self.ui.setupUi(self.window)
            self.window.show()
        else :
            pass



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Academics_Win = QtWidgets.QDialog()
    ui = Ui_Academics_Win()
    ui.setupUi(Academics_Win)
    Academics_Win.show()
    sys.exit(app.exec_())
