# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BusTimes_Win.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtWebEngineWidgets
import busTimes


class Ui_busInfo(object):
    def setupUi(self, busInfo):
        busInfo.setObjectName("busInfo")
        busInfo.resize(1605, 820)
        busInfo.setStyleSheet("background-image: url(:/Background/QRC/magicpattern-gradient-1690353787077.jpeg);")
        self.gridLayout = QtWidgets.QGridLayout(busInfo)
        self.gridLayout.setObjectName("gridLayout")
        self.BusInfo_Label = QtWidgets.QLabel(busInfo)
        self.BusInfo_Label.setMaximumSize(QtCore.QSize(1600, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(20)
        self.BusInfo_Label.setFont(font)
        self.BusInfo_Label.setStyleSheet("QLabel\n"
"{\n"
"background: transparent;\n"
"}\n"
"")
        self.BusInfo_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.BusInfo_Label.setObjectName("BusInfo_Label")
        self.gridLayout.addWidget(self.BusInfo_Label, 0, 0, 1, 6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(23)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout.addLayout(self.horizontalLayout_2, 8, 4, 1, 2)
        self.mapView = QtWebEngineWidgets.QWebEngineView(busInfo)
        self.mapView.setMinimumSize(QtCore.QSize(1100, 0))
        self.mapView.setUrl(QtCore.QUrl("about:blank"))
        self.mapView.setObjectName("mapView")
        self.gridLayout.addWidget(self.mapView, 7, 0, 1, 1)
        self.busTable = QtWidgets.QTableWidget(busInfo)
        self.busTable.setMinimumSize(QtCore.QSize(463, 500))
        self.busTable.setStyleSheet("QLabel\n"
"{\n"
"background: transparent;\n"
"}\n"
"")
        self.busTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.busTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.busTable.setObjectName("busTable")
        self.busTable.setColumnCount(3)
        self.busTable.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.busTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.busTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.busTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.busTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.busTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.busTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.busTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.busTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.busTable.setItem(1, 0, item)
        self.busTable.horizontalHeader().setDefaultSectionSize(151)
        self.busTable.verticalHeader().setDefaultSectionSize(34)
        self.gridLayout.addWidget(self.busTable, 7, 4, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(14)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.submit = QtWidgets.QPushButton(busInfo)
        self.submit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.submit.setFont(font)
        self.submit.setStyleSheet("QPushButton{\n"
"background-color: none;\n"
"color:white;\n"
"border-width: 2px;\n"
"font:bold 25px;\n"
"border-radius: 8px;\n"
"padding: 5px;\n"
"border: 2px solid blue;\n"
"border-style: groove;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: white;\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 170, 0);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/QRC/submitIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.submit.setIcon(icon)
        self.submit.setIconSize(QtCore.QSize(26, 30))
        self.submit.setObjectName("submit")
        self.submit.clicked.connect(self.pressed)
        self.verticalLayout_3.addWidget(self.submit)
        self.homeButton = QtWidgets.QPushButton(busInfo)
        self.homeButton.setStyleSheet("QPushButton{\n"
"background-color: none;\n"
"color:white;\n"
"border-width: 2px;\n"
"font:bold 25px;\n"
"border-radius: 8px;\n"
"padding: 5px;\n"
"border: 2px solid blue;\n"
"border-style: groove;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: white;\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 170, 0);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/QRC/homeIcon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeButton.setIcon(icon1)
        self.homeButton.setIconSize(QtCore.QSize(25, 25))
        self.homeButton.setObjectName("homeButton")
        self.homeButton.clicked.connect(lambda: self.HomeButton('Home'))
        self.homeButton.clicked.connect(busInfo.close)
        self.verticalLayout_3.addWidget(self.homeButton)
        self.gridLayout.addLayout(self.verticalLayout_3, 2, 5, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.boardingPointLabel = QtWidgets.QLabel(busInfo)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(16)
        self.boardingPointLabel.setFont(font)
        self.boardingPointLabel.setStyleSheet("QLabel\n"
"{\n"
"background: transparent;\n"
"}\n"
"")
        self.boardingPointLabel.setScaledContents(True)
        self.boardingPointLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.boardingPointLabel.setObjectName("boardingPointLabel")
        self.verticalLayout.addWidget(self.boardingPointLabel)
        self.comboBox = QtWidgets.QComboBox(busInfo)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setEditable(False)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.gridLayout.addLayout(self.verticalLayout, 2, 4, 1, 1)
        self.busDetails = QtWidgets.QLabel(busInfo)
        self.busDetails.setMinimumSize(QtCore.QSize(150, 0))
        self.busDetails.setStyleSheet("QLabel\n"
"{\n"
"background: transparent;\n"
"}\n"
"")
        self.busDetails.setObjectName("busDetails")
        self.gridLayout.addWidget(self.busDetails, 2, 0, 2, 1)

        self.retranslateUi(busInfo)
        QtCore.QMetaObject.connectSlotsByName(busInfo)

    def retranslateUi(self, busInfo):
        _translate = QtCore.QCoreApplication.translate
        busInfo.setWindowTitle(_translate("busInfo", "Dialog"))
        self.BusInfo_Label.setText(_translate("busInfo", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">Bus Information</span></p></body></html>"))
        item = self.busTable.horizontalHeaderItem(0)
        item.setText(_translate("busInfo", "Pick Up Time"))
        item = self.busTable.horizontalHeaderItem(1)
        item.setText(_translate("busInfo", "Location"))
        item = self.busTable.horizontalHeaderItem(2)
        item.setText(_translate("busInfo", "Drop Off Time"))
        __sortingEnabled = self.busTable.isSortingEnabled()
        self.busTable.setSortingEnabled(False)
        self.busTable.setSortingEnabled(__sortingEnabled)
        self.submit.setText(_translate("busInfo", " Submit"))
        self.homeButton.setText(_translate("busInfo", " Home"))
        self.boardingPointLabel.setText(_translate("busInfo", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">Boarding Point</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("busInfo", "Select you boarding point"))
        self.comboBox.setItemText(1, _translate("busInfo", "Kerala"))
        self.comboBox.setItemText(2, _translate("busInfo", "Chennai"))
        self.comboBox.setItemText(3, _translate("busInfo", "Maharasthra"))
        self.comboBox.setItemText(4, _translate("busInfo", "Karnataka"))
        self.busDetails.setText(_translate("busInfo", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">BusInfo</span></p></body></html>"))

    def pressed(self):
        _translate = QtCore.QCoreApplication.translate
        if self.comboBox.currentText() == 'Kerala':
            print('Kerala selected')
            self.busInfo('A')
            self.busDescription('A')
            self.busMap('A')
        elif self.comboBox.currentText() == 'Chennai':
            print('Chennai selected')
        elif self.comboBox.currentText() == 'Maharashtra':
            print('Maharashtra selected')
        elif self.comboBox.currentText() == 'Karnataka':
            print('Karnataka selected')
        else:
            print("Select an option from the drop-down menu then press on 'Submit' button ")
            self.busInfo('None')
            self.busDescription('None')
            self.busMap('None')

    def busInfo(self, busID):
        _translate = QtCore.QCoreApplication.translate
        global item
        if busID == 'A':
            stops = 3  # Number of stops to be decided by the user
            for i in range(0, stops):
                for j in range(0, stops):
                    item = QtWidgets.QTableWidgetItem()  # Declaring how many items will be added row and column wise
                    self.busTable.setItem(i, j, item)
            """        
            for i in range(0,stops):
                for j in range(0, stops):
            """
            item = self.busTable.item(0, 0)
            item.setText(_translate("busInfo", "7:35 AM"))
            item = self.busTable.item(0, 1)
            item.setText(_translate("busInfo", "Cochin"))
            item = self.busTable.item(0, 2)
            item.setText(_translate("busInfo", "4:30 PM"))
            item = self.busTable.item(1, 0)
            item.setText(_translate("busInfo", "7:35 AM"))
            item = self.busTable.item(1, 1)
            item.setText(_translate("busInfo", "Cochin"))
            item = self.busTable.item(1, 2)
            item.setText(_translate("busInfo", "4:30 PM"))
        elif busID == 'B':
            pass
        elif busID == 'None':
            pass
            self.busTable.clearContents()
        else:
            pass

    def busDescription(self, busID):
        _translate = QtCore.QCoreApplication.translate
        self.busDetails.setText(_translate("busInfo",
                                           "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">BusInfo</span></p></body></html>"))
        if busID == 'A':
            self.busDetails.setText(
                _translate("busInfo",
                           "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Bus No:  <br> Bus Driver: <br> Contact Number: <br> Office Number: </span></p></body></html>"))
        elif busID == 'B':
            pass
        elif busID == 'None':
            self.busDetails.setText(
                _translate("busInfo",
                           "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Select an option from the drop-down menu <br> then press on 'Submit' button</span></p></body></html>"))
        else:
            pass

    def busMap(self, busID):
        if busID == 'A':
            self.mapView.setHtml(
                '<iframe src="https://www.google.com/maps/embed?pb=!1m28!1m12!1m3!1d504189.32411062706!2d76.31890577136615!3d9.156358159689153!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m13!3e6!4m5!1s0x3b062ba16c6b435f%3A0xbe2b02f68f8dd06e!2sKottayam%2C%20Kerala!3m2!1d9.591566799999999!2d76.5221531!4m5!1s0x3b05e916e5a3d259%3A0xae423fbee16bb083!2sMarthoma%20Central%20School%2C%20Cherunniyoor%2C%20695142%2C%20Cherunniyoor%2C%20Kerala!3m2!1d8.7200321!2d76.7607005!5e0!3m2!1sen!2sin!4v1691442324356!5m2!1sen!2sin" width="1080" height="530" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>')
        elif busID == 'B':
            pass
        elif busID == 'None':
            self.mapView.setUrl(QtCore.QUrl('about:blank'))
        else:
            pass

    def HomeButton(self, button):
        """

        :param button:
        :return:
        """
        if button == 'Home':
            from School_Reception import Ui_MainWindow
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_MainWindow()
            self.ui.setupUi(self.window)
            self.window.show()
        else:
            pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    busInfo = QtWidgets.QDialog()
    ui = Ui_busInfo()
    ui.setupUi(busInfo)
    busInfo.show()
    sys.exit(app.exec_())
