# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ComboBoxes.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.combo_x = QtWidgets.QComboBox(self.centralwidget)
        self.combo_x.setGeometry(QtCore.QRect(40, 70, 211, 121))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.combo_x.setFont(font)
        self.combo_x.setObjectName("combo_x")
        self.combo_x.addItem("")
        self.combo_x.addItem("")
        self.combo_y = QtWidgets.QComboBox(self.centralwidget)
        self.combo_y.setGeometry(QtCore.QRect(540, 70, 211, 101))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.combo_y.setFont(font)
        self.combo_y.setObjectName("combo_y")
        self.combo_y.addItem("")
        self.combo_y.addItem("")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(330, 340, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.submit.setFont(font)
        self.submit.setObjectName("submit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 250, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.submit.clicked.connect(self.pressed)
        """
        self.combo_x.addItem("Hello")  # To add an item
        index = self.combo_x.findText("Hello", QtCore.Qt.MatchFixedString) #If the element isn't there it print out -1
        self.combo_x.setCurrentIndex(index)        
        """
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.combo_x.setItemText(0, _translate("MainWindow", "0"))
        self.combo_x.setItemText(1, _translate("MainWindow", "1"))
        self.combo_y.setItemText(0, _translate("MainWindow", "0"))
        self.combo_y.setItemText(1, _translate("MainWindow", "1"))
        self.submit.setText(_translate("MainWindow", "SUBMIT"))
        self.label.setText(_translate("MainWindow", "X XOR Y ="))

    def pressed(self):
        x = int(self.combo_x.currentText())
        y = int(self.combo_y.currentText())
        print(self.combo_x.currentText())
        print(self.combo_y.currentText())
        """
        xor = (x and not y) or (not x and y)
        if xor == True:
            xor = 1
        else:
            xor = 0

        self.label.setText("X XOR Y =" + str(xor))
        """


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
