# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Facilities_Win.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Facilities(object):
    def setupUi(self, Facilities):
        buttonFontsize = 8
        Facilities.setObjectName("Facilities")
        Facilities.resize(804, 511)
        Facilities.setWindowIcon(QtGui.QIcon('Icons/facilities_Win_icon.png'))
        self.centralwidget = QtWidgets.QWidget(Facilities)
        self.centralwidget.setObjectName("centralwidget")
        self.Images = QtWidgets.QLabel(self.centralwidget)
        self.Images.setGeometry(QtCore.QRect(10, 10, 641, 261))
        self.Images.setText("")
        self.Images.setPixmap(QtGui.QPixmap("Images/winter-blue-pink-gradient-background-vector_53876-117275.jpg"))
        self.Images.setObjectName("Images")
        self.Images.setScaledContents(True)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 290, 641, 191))
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(661, 13, 133, 471))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labs = QtWidgets.QPushButton(self.widget)
        self.labs.setAutoDefault(True)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(buttonFontsize)
        self.labs.setFont(font)
        self.labs.setObjectName("labs")
        self.labs.clicked.connect(lambda: self.user_response_button('labs'))
        self.verticalLayout.addWidget(self.labs)
        self.library = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(buttonFontsize)
        self.library.setFont(font)
        self.library.setObjectName("library")
        self.library.clicked.connect(lambda: self.user_response_button('library'))
        self.verticalLayout.addWidget(self.library)
        self.smartClass = QtWidgets.QPushButton(self.widget)
        self.smartClass.setObjectName("smartClass")
        self.smartClass.clicked.connect(lambda: self.user_response_button('smart class'))
        self.verticalLayout.addWidget(self.smartClass)
        self.sportAndGames = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(buttonFontsize)
        self.sportAndGames.setFont(font)
        self.sportAndGames.setObjectName("sportAndGames")
        self.sportAndGames.clicked.connect(lambda: self.user_response_button('sport and games'))
        self.verticalLayout.addWidget(self.sportAndGames)
        self.guideAndcounsel = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(buttonFontsize)
        self.guideAndcounsel.setFont(font)
        self.guideAndcounsel.setObjectName("guideAndcounsel")
        self.guideAndcounsel.clicked.connect(lambda: self.user_response_button('guide and council'))
        self.verticalLayout.addWidget(self.guideAndcounsel)
        self.fineArts = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(buttonFontsize)
        self.fineArts.setFont(font)
        self.fineArts.setObjectName("fineArts")
        self.fineArts.clicked.connect(lambda: self.user_response_button('fine arts'))
        self.verticalLayout.addWidget(self.fineArts)
        self.auditorium = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(buttonFontsize)
        self.auditorium.setFont(font)
        self.auditorium.setObjectName("auditorium")
        self.auditorium.clicked.connect(lambda: self.user_response_button('auditorium'))
        self.verticalLayout.addWidget(self.auditorium)

        Facilities.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(Facilities)
        self.statusBar.setObjectName("statusBar")
        Facilities.setStatusBar(self.statusBar)

        self.retranslateUi(Facilities)
        QtCore.QMetaObject.connectSlotsByName(Facilities)

    def retranslateUi(self, Facilities):
        _translate = QtCore.QCoreApplication.translate
        Facilities.setWindowTitle(_translate("Facilities", "Facility Info"))
        self.textBrowser.setPlaceholderText(_translate("Facilities", "Interact with side buttons to learn more about our school\'s facilities"))
        self.labs.setText(_translate("Facilities", "Labs"))
        self.library.setText(_translate("Facilities", "Library"))
        self.smartClass.setText(_translate("Facilities", "Smart Class"))
        self.sportAndGames.setText(_translate("Facilities", "Sports And Games"))
        self.guideAndcounsel.setText(_translate("Facilities", "Guidance And Counselling"))
        self.fineArts.setText(_translate("Facilities", "Fine Arts"))
        self.auditorium.setText(_translate("Facilities", "Auditorium"))


    def user_response_button(self, button):
        _translate = QtCore.QCoreApplication.translate
        if button == 'labs':
            print('Labs Clicked')
            self.Images.setPixmap(QtGui.QPixmap("Images/img_1.jpg"))
            self.textBrowser.setHtml(_translate("Facilities",
                                                "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
                                                "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style "
                                                "type=\"text/css\">\n"
                                                "p, li { white-space: pre-wrap; }\n"
                                                "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; "
                                                "font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                                "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; "
                                                "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                                                "style=\" font-family:\'Open Sans,Arial,sans-serif\'; color:#000000; "
                                                "background-color:#ffffff;\">Lorem ipsum dolor sit amet, consectetur "
                                                "adipiscing elit. Praesent dapibus dapibus urna nec dapibus. Praesent "
                                                "at nunc at urna sagittis scelerisque. In hac habitasse platea "
                                                "dictumst. Vivamus luctus pellentesque velit, ut tincidunt dolor "
                                                "suscipit id. Proin ac scelerisque nibh. Maecenas sit amet ligula "
                                                "dui. Nunc mollis magna dolor, quis tincidunt sem convallis a. In "
                                                "rutrum imperdiet euismod. Phasellus non augue leo. Phasellus "
                                                "accumsan et tortor non dapibus.</span></p></body></html>"))

        elif button == 'library':
            print('Library Clicked')
            self.Images.setPixmap(QtGui.QPixmap("Images/img_3.jpg"))
            self.textBrowser.setHtml(_translate("Facilities",
                                                "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
                                                "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style "
                                                "type=\"text/css\">\n"
                                                "p, li { white-space: pre-wrap; }\n"
                                                "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; "
                                                "font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                                "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; "
                                                "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                                                "style=\" font-family:\'Open Sans,Arial,sans-serif\'; color:#000000; "
                                                "background-color:#ffffff;\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus dapibus urna nec dapibus. Praesent at nunc at urna sagittis scelerisque. In hac habitasse platea dictumst. Vivamus luctus pellentesque velit, ut tincidunt dolor suscipit id. Proin ac scelerisque nibh. Maecenas sit amet ligula dui. Nunc mollis magna dolor, quis tincidunt sem convallis a. In rutrum imperdiet euismod. Phasellus non augue leo. Phasellus accumsan et tortor non dapibus.</span></p></body></html>"))
        elif button == 'smart class':
            print('Smart Class Clicked')
            self.Images.setPixmap(QtGui.QPixmap("Images/img_4.jpg"))
            self.textBrowser.setHtml(_translate("Facilities",
                                                "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
                                                "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style "
                                                "type=\"text/css\">\n"
                                                "p, li { white-space: pre-wrap; }\n"
                                                "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; "
                                                "font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                                "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; "
                                                "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                                                "style=\" font-family:\'Open Sans,Arial,sans-serif\'; color:#000000; "
                                                "background-color:#ffffff;\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus dapibus urna nec dapibus. Praesent at nunc at urna sagittis scelerisque. In hac habitasse platea dictumst. Vivamus luctus pellentesque velit, ut tincidunt dolor suscipit id. Proin ac scelerisque nibh. Maecenas sit amet ligula dui. Nunc mollis magna dolor, quis tincidunt sem convallis a. In rutrum imperdiet euismod. Phasellus non augue leo. Phasellus accumsan et tortor non dapibus.</span></p></body></html>"))
        elif button == 'sport and games':
            print('Sport and Games Clicked')
            self.Images.setPixmap(QtGui.QPixmap("Images/img_5.jpg"))
            self.textBrowser.setHtml(_translate("Facilities",
                                                "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
                                                "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style "
                                                "type=\"text/css\">\n"
                                                "p, li { white-space: pre-wrap; }\n"
                                                "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; "
                                                "font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                                "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; "
                                                "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                                                "style=\" font-family:\'Open Sans,Arial,sans-serif\'; color:#000000; "
                                                "background-color:#ffffff;\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus dapibus urna nec dapibus. Praesent at nunc at urna sagittis scelerisque. In hac habitasse platea dictumst. Vivamus luctus pellentesque velit, ut tincidunt dolor suscipit id. Proin ac scelerisque nibh. Maecenas sit amet ligula dui. Nunc mollis magna dolor, quis tincidunt sem convallis a. In rutrum imperdiet euismod. Phasellus non augue leo. Phasellus accumsan et tortor non dapibus.</span></p></body></html>"))
        elif button == 'guide and council':
            self.Images.setPixmap(QtGui.QPixmap("Images/img_2.jpg"))
            print('Guidance And Counselling Clicked')
            self.textBrowser.setHtml(_translate("Facilities",
                                                "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
                                                "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style "
                                                "type=\"text/css\">\n"
                                                "p, li { white-space: pre-wrap; }\n"
                                                "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; "
                                                "font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                                "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; "
                                                "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                                                "style=\" font-family:\'Open Sans,Arial,sans-serif\'; color:#000000; "
                                                "background-color:#ffffff;\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus dapibus urna nec dapibus. Praesent at nunc at urna sagittis scelerisque. In hac habitasse platea dictumst. Vivamus luctus pellentesque velit, ut tincidunt dolor suscipit id. Proin ac scelerisque nibh. Maecenas sit amet ligula dui. Nunc mollis magna dolor, quis tincidunt sem convallis a. In rutrum imperdiet euismod. Phasellus non augue leo. Phasellus accumsan et tortor non dapibus.</span></p></body></html>"))
        elif button == 'fine arts':
            print('Fine Arts Clicked')
            self.Images.setPixmap(QtGui.QPixmap("Images/img_6.jpg"))
            self.textBrowser.setHtml(_translate("Facilities",
                                                "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
                                                "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style "
                                                "type=\"text/css\">\n"
                                                "p, li { white-space: pre-wrap; }\n"
                                                "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; "
                                                "font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                                "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; "
                                                "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                                                "style=\" font-family:\'Open Sans,Arial,sans-serif\'; color:#000000; "
                                                "background-color:#ffffff;\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus dapibus urna nec dapibus. Praesent at nunc at urna sagittis scelerisque. In hac habitasse platea dictumst. Vivamus luctus pellentesque velit, ut tincidunt dolor suscipit id. Proin ac scelerisque nibh. Maecenas sit amet ligula dui. Nunc mollis magna dolor, quis tincidunt sem convallis a. In rutrum imperdiet euismod. Phasellus non augue leo. Phasellus accumsan et tortor non dapibus.</span></p></body></html>"))
        else:
            print('Auditorium Clicked')
            self.Images.setPixmap(QtGui.QPixmap("Images/img_7.jpg"))
            self.textBrowser.setHtml(_translate("Facilities",
                                                "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
                                                "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style "
                                                "type=\"text/css\">\n"
                                                "p, li { white-space: pre-wrap; }\n"
                                                "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; "
                                                "font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                                "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; "
                                                "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                                                "style=\" font-family:\'Open Sans,Arial,sans-serif\'; color:#000000; "
                                                "background-color:#ffffff;\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus dapibus urna nec dapibus. Praesent at nunc at urna sagittis scelerisque. In hac habitasse platea dictumst. Vivamus luctus pellentesque velit, ut tincidunt dolor suscipit id. Proin ac scelerisque nibh. Maecenas sit amet ligula dui. Nunc mollis magna dolor, quis tincidunt sem convallis a. In rutrum imperdiet euismod. Phasellus non augue leo. Phasellus accumsan et tortor non dapibus.</span></p></body></html>"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Facilities = QtWidgets.QMainWindow()
    ui = Ui_Facilities()
    ui.setupUi(Facilities)
    Facilities.show()
    sys.exit(app.exec_())
