# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Faculty_Win.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtWebEngineWidgets
import Faculty


class Ui_Faculty(object):
    def setupUi(self, Faculty):
        Faculty.setObjectName("Faculty")
        Faculty.resize(1600, 820)
        Faculty.setStyleSheet("background-image: url(:/Background/QRC/magicpattern-gradient-1690353787077.jpeg);")
        Faculty.setSizeGripEnabled(False)
        Faculty.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(Faculty)
        self.gridLayout.setObjectName("gridLayout")
        self.Faculty_Label = QtWidgets.QLabel(Faculty)
        self.Faculty_Label.setMinimumSize(QtCore.QSize(0, 0))
        self.Faculty_Label.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(20)
        self.Faculty_Label.setFont(font)
        self.Faculty_Label.setStyleSheet("QLabel\n"
"{\n"
"background: transparent;\n"
"}")
        self.Faculty_Label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Faculty_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Faculty_Label.setObjectName("Faculty_Label")
        self.gridLayout.addWidget(self.Faculty_Label, 0, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.dept_of_lang = QtWidgets.QPushButton(Faculty)
        self.dept_of_lang.setStyleSheet("QPushButton{\n"
"background-color: none;\n"
"color:white;\n"
"border-width: 2px;\n"
"font:bold 25px;\n"
"border-radius: 8px;\n"
"padding: 5px;\n"
"border: 2px solid blue;\n"
"border-style: groove;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: white;\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 170, 0);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/QRC/languages.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dept_of_lang.setIcon(icon)
        self.dept_of_lang.setIconSize(QtCore.QSize(28, 28))
        self.dept_of_lang.setObjectName("dept_of_lang")
        self.dept_of_lang.clicked.connect(lambda: self.open_dept('dept_of_lang'))
        self.verticalLayout.addWidget(self.dept_of_lang)
        self.dept_of_maths = QtWidgets.QPushButton(Faculty)
        self.dept_of_maths.setStyleSheet("QPushButton{\n"
"background-color: none;\n"
"color:white;\n"
"border-width: 2px;\n"
"font:bold 25px;\n"
"border-radius: 8px;\n"
"padding: 5px;\n"
"border: 2px solid blue;\n"
"border-style: groove;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: white;\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 170, 0);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icon/QRC/mathsIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dept_of_maths.setIcon(icon1)
        self.dept_of_maths.setIconSize(QtCore.QSize(28, 28))
        self.dept_of_maths.setObjectName("dept_of_maths")
        self.dept_of_maths.clicked.connect(lambda: self.open_dept('dept_of_maths'))
        self.verticalLayout.addWidget(self.dept_of_maths)
        self.dept_of_social_sci = QtWidgets.QPushButton(Faculty)
        self.dept_of_social_sci.setStyleSheet("QPushButton{\n"
"background-color: none;\n"
"color:white;\n"
"border-width: 2px;\n"
"font:bold 25px;\n"
"border-radius: 8px;\n"
"padding: 5px;\n"
"border: 2px solid blue;\n"
"border-style: groove;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: white;\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 170, 0);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icon/QRC/ssIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dept_of_social_sci.setIcon(icon2)
        self.dept_of_social_sci.setIconSize(QtCore.QSize(28, 28))
        self.dept_of_social_sci.setObjectName("dept_of_social_sci")
        self.verticalLayout.addWidget(self.dept_of_social_sci)
        self.dept_of_pe = QtWidgets.QPushButton(Faculty)
        self.dept_of_pe.setStyleSheet("QPushButton{\n"
"background-color: none;\n"
"color:white;\n"
"border-width: 2px;\n"
"font:bold 25px;\n"
"border-radius: 8px;\n"
"padding: 5px;\n"
"border: 2px solid blue;\n"
"border-style: groove;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: white;\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 170, 0);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icon/QRC/peIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dept_of_pe.setIcon(icon3)
        self.dept_of_pe.setIconSize(QtCore.QSize(28, 28))
        self.dept_of_pe.setObjectName("dept_of_pe")
        self.verticalLayout.addWidget(self.dept_of_pe)
        self.dept_of_sci = QtWidgets.QPushButton(Faculty)
        self.dept_of_sci.setStyleSheet("QPushButton{\n"
"background-color: none;\n"
"color:white;\n"
"border-width: 2px;\n"
"font:bold 25px;\n"
"border-radius: 8px;\n"
"padding: 5px;\n"
"border: 2px solid blue;\n"
"border-style: groove;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: white;\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 170, 0);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icon/QRC/scienceIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dept_of_sci.setIcon(icon4)
        self.dept_of_sci.setIconSize(QtCore.QSize(28, 28))
        self.dept_of_sci.setObjectName("dept_of_sci")
        self.verticalLayout.addWidget(self.dept_of_sci)
        self.dept_of_fine_arts = QtWidgets.QPushButton(Faculty)
        self.dept_of_fine_arts.setStyleSheet("QPushButton{\n"
"background-color: none;\n"
"color:white;\n"
"border-width: 2px;\n"
"font:bold 25px;\n"
"border-radius: 8px;\n"
"padding: 5px;\n"
"border: 2px solid blue;\n"
"border-style: groove;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: white;\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 170, 0);\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icon/QRC/fineartsIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dept_of_fine_arts.setIcon(icon5)
        self.dept_of_fine_arts.setIconSize(QtCore.QSize(28, 28))
        self.dept_of_fine_arts.setObjectName("dept_of_fine_arts")
        self.verticalLayout.addWidget(self.dept_of_fine_arts)
        self.dept_of_comp_sci = QtWidgets.QPushButton(Faculty)
        self.dept_of_comp_sci.setStyleSheet("QPushButton{\n"
"background-color: none;\n"
"color:white;\n"
"border-width: 2px;\n"
"font:bold 25px;\n"
"border-radius: 8px;\n"
"padding: 5px;\n"
"border: 2px solid blue;\n"
"border-style: groove;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: white;\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 170, 0);\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icon/QRC/csIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dept_of_comp_sci.setIcon(icon6)
        self.dept_of_comp_sci.setIconSize(QtCore.QSize(28, 28))
        self.dept_of_comp_sci.setObjectName("dept_of_comp_sci")
        self.verticalLayout.addWidget(self.dept_of_comp_sci)
        self.other_dept = QtWidgets.QPushButton(Faculty)
        self.other_dept.setStyleSheet("QPushButton{\n"
"background-color: none;\n"
"color:white;\n"
"border-width: 2px;\n"
"font:bold 25px;\n"
"border-radius: 8px;\n"
"padding: 5px;\n"
"border: 2px solid blue;\n"
"border-style: groove;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: white;\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 170, 0);\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icon/QRC/otherIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.other_dept.setIcon(icon7)
        self.other_dept.setIconSize(QtCore.QSize(28, 28))
        self.other_dept.setObjectName("other_dept")
        self.verticalLayout.addWidget(self.other_dept)
        self.homeButton = QtWidgets.QPushButton(Faculty)
        self.homeButton.setStyleSheet("QPushButton{\n"
"background-color: none;\n"
"color:white;\n"
"border-width: 2px;\n"
"font:bold 25px;\n"
"border-radius: 8px;\n"
"padding: 5px;\n"
"border: 2px solid blue;\n"
"border-style: groove;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: white;\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"border-style:solid;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 170, 0);\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icon/QRC/homeIcon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeButton.setIcon(icon8)
        self.homeButton.setIconSize(QtCore.QSize(30, 26))
        self.homeButton.setObjectName("homeButton")
        self.homeButton.clicked.connect(lambda: self.open_dept('Home'))
        self.homeButton.clicked.connect(Faculty.close)
        self.verticalLayout.addWidget(self.homeButton)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.deptView = QtWebEngineWidgets.QWebEngineView(Faculty)
        self.deptView.setMinimumSize(QtCore.QSize(790, 700))
        self.deptView.setStyleSheet("")
        self.deptView.setUrl(QtCore.QUrl("about:blank"))
        self.deptView.setObjectName("deptView")
        self.deptView.settings().setAttribute(QtWebEngineWidgets.QWebEngineSettings.PdfViewerEnabled, True)
        self.deptView.settings().setAttribute(QtWebEngineWidgets.QWebEngineSettings.PluginsEnabled, True)
        self.gridLayout.addWidget(self.deptView, 1, 0, 1, 1)

        self.retranslateUi(Faculty)
        QtCore.QMetaObject.connectSlotsByName(Faculty)

    def retranslateUi(self, Faculty):
        _translate = QtCore.QCoreApplication.translate
        Faculty.setWindowTitle(_translate("Faculty", "Dialog"))
        self.Faculty_Label.setText(_translate("Faculty", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">Faculty</span></p></body></html>"))
        self.dept_of_lang.setText(_translate("Faculty", " Department of Language"))
        self.dept_of_maths.setText(_translate("Faculty", " Department of Mathematics"))
        self.dept_of_social_sci.setText(_translate("Faculty", " Department of Social Science"))
        self.dept_of_pe.setText(_translate("Faculty", " Department of Physical Education and Yoga"))
        self.dept_of_sci.setText(_translate("Faculty", " Department of Science"))
        self.dept_of_fine_arts.setText(_translate("Faculty", " Department of Fine Arts"))
        self.dept_of_comp_sci.setText(_translate("Faculty", " Department of Computer Science"))
        self.other_dept.setText(_translate("Faculty", " Other Departments"))
        self.homeButton.setText(_translate("Faculty", " Home"))

    def open_dept(self, button):
        """

        :param button:
        :return:
        """
        if button == 'dept_of_lang':
            url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRrrF8b43rH82sYnXSv34mqJpjYy8E-N-m3Aya18NeV1lpKpbxeNRJLsH31KOU2oUMCpHxANVRk0BVl/pubhtml'
            self.deptView.setUrl(QtCore.QUrl(url))
        elif button == 'dept_of_maths':
            url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRrrF8b43rH82sYnXSv34mqJpjYy8E-N-m3Aya18NeV1lpKpbxeNRJLsH31KOU2oUMCpHxANVRk0BVl/pubhtml'
            self.deptView.setUrl(QtCore.QUrl(url))
        elif button == 'Home':
            from School_Reception import Ui_MainWindow
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_MainWindow()
            self.ui.setupUi(self.window)
            self.window.show()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Faculty = QtWidgets.QDialog()
    ui = Ui_Faculty()
    ui.setupUi(Faculty)
    Faculty.show()
    sys.exit(app.exec_())
