# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BusTimes_Win.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtWebEngineWidgets


class Ui_busInfo(object):
    def setupUi(self, busInfo):
        buttonFontsize=10
        busInfo.setObjectName("busInfo")
        busInfo.resize(648, 477)
        busInfo.setWindowIcon(QtGui.QIcon('Icons/busInfo_Win_icon.png')) # Attribution: <a href="https://www.flaticon.com/free-icons/bus" title="bus icons">Bus icons created by Freepik - Flaticon</a>
        self.BusTimes_Label = QtWidgets.QLabel(busInfo)
        self.BusTimes_Label.setGeometry(QtCore.QRect(210, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(20)
        self.BusTimes_Label.setFont(font)
        self.BusTimes_Label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.BusTimes_Label.setObjectName("BusTimes_Label")
        self.mapView = QtWebEngineWidgets.QWebEngineView(busInfo)
        self.mapView.setGeometry(QtCore.QRect(340, 190, 294, 274))
        self.mapView.setUrl(QtCore.QUrl("about:blank"))
        self.mapView.setObjectName("mapView")
        self.busTable = QtWidgets.QTableWidget(busInfo)
        self.busTable.setGeometry(QtCore.QRect(0, 190, 331, 271))
        self.busTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.busTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.busTable.setObjectName("busTable")
        self.busTable.setColumnCount(3)
        self.busTable.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.busTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.busTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.busTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.busTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.busTable.setHorizontalHeaderItem(2, item)

        self.submit = QtWidgets.QPushButton(busInfo)
        self.submit.setGeometry(QtCore.QRect(250, 130, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(buttonFontsize)
        self.submit.setFont(font)
        self.submit.setObjectName("submit")
        self.submit.clicked.connect(self.pressed)

        self.busDetails = QtWidgets.QLabel(busInfo)
        self.busDetails.setGeometry(QtCore.QRect(340, 50, 271, 131))
        self.busDetails.setObjectName("busDetails")
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(buttonFontsize)
        self.busDetails.setFont(font)

        self.widget = QtWidgets.QWidget(busInfo)
        self.widget.setGeometry(QtCore.QRect(10, 70, 231, 98))
        self.widget.setObjectName("widget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.comboBox = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setEditable(False)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)

        self.retranslateUi(busInfo)
        QtCore.QMetaObject.connectSlotsByName(busInfo)

    def retranslateUi(self, busInfo):
        _translate = QtCore.QCoreApplication.translate
        busInfo.setWindowTitle(_translate("busInfo", "Bus Information"))
        self.BusTimes_Label.setText(_translate("busInfo", "Bus Information"))
        item = self.busTable.horizontalHeaderItem(0)
        item.setText(_translate("busInfo", "Pick Up Time"))
        item = self.busTable.horizontalHeaderItem(1)
        item.setText(_translate("busInfo", "Location"))
        item = self.busTable.horizontalHeaderItem(2)
        item.setText(_translate("busInfo", "Drop Off Time"))
        __sortingEnabled = self.busTable.isSortingEnabled()
        self.busTable.setSortingEnabled(False)
        self.busTable.setSortingEnabled(__sortingEnabled)
        self.busDetails.setText(_translate("busInfo", "Select an option from the drop-down menu \nthen press on 'Submit' button "))
        self.submit.setText(_translate("busInfo", "Submit"))
        self.label.setText(_translate("busInfo", "Boarding Point"))
        self.comboBox.setItemText(0, _translate("busInfo", "Select you boarding point"))
        self.comboBox.setItemText(1, _translate("busInfo", "Kerala"))
        self.comboBox.setItemText(2, _translate("busInfo", "Chennai"))
        self.comboBox.setItemText(3, _translate("busInfo", "Maharashtra"))
        self.comboBox.setItemText(4, _translate("busInfo", "Karnataka"))

    def pressed(self):
        _translate = QtCore.QCoreApplication.translate
        if self.comboBox.currentText() == 'Kerala':
            print('Kerala selected')
            self.busInfo('A')
            self.busDescription('A')
            self.busMap('A')
        elif self.comboBox.currentText() == 'Chennai':
            print('Chennai selected')
        elif self.comboBox.currentText() == 'Maharashtra':
            print('Maharashtra selected')
        elif self.comboBox.currentText() == 'Karnataka':
            print('Karnataka selected')
        else:
            print("Select an option from the drop-down menu then press on 'Submit' button ")
            self.busInfo('None')
            self.busDescription('None')
            self.busMap('None')

    def busInfo(self, busID):
        _translate = QtCore.QCoreApplication.translate
        global item
        if busID == 'A':
            stops=3
            for i in range(0, stops):
                for j in range(0, stops):
                    item = QtWidgets.QTableWidgetItem()  # Declaring how many items will be added row and column wise
                    self.busTable.setItem(i, j, item)
            """        
            for i in range(0,stops):
                for j in range(0, stops):
            """
            item = self.busTable.item(0, 0)
            item.setText(_translate("busInfo", "7:35 AM"))
            item = self.busTable.item(0, 1)
            item.setText(_translate("busInfo", "Cochin"))
            item = self.busTable.item(0, 2)
            item.setText(_translate("busInfo", "4:30 PM"))
            item = self.busTable.item(1, 0)
            item.setText(_translate("busInfo", "7:35 AM"))
            item = self.busTable.item(1, 1)
            item.setText(_translate("busInfo", "Cochin"))
            item = self.busTable.item(1, 2)
            item.setText(_translate("busInfo", "4:30 PM"))
        elif busID == 'B':
            pass
        elif busID == 'None':
            pass
            self.busTable.clearContents()
        else:
            pass


    def busDescription(self,busID):
        _translate = QtCore.QCoreApplication.translate
        if busID == 'A':
            self.busDetails.setText(_translate("busInfo", " Bus No:  \n Bus Driver: \n Contact Number: \n Office Number: "))
        elif busID == 'B':
            pass
        elif busID == 'None':
            self.busDetails.setText(_translate("busInfo", "Select an option from the drop-down menu \nthen press on 'Submit' button "))
        else:
            pass
    def busMap(self,busID):
        if busID == 'A':
            self.mapView.setHtml('<iframe src="https://www.google.com/maps/embed?pb=!1m28!1m12!1m3!1d503481.64879584627!2d76.30387664657918!3d9.64250306356781!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m13!3e6!4m5!1s0x3b06152f4f9705d7%3A0x4d93dd296d4b4abc!2sPathanamthitta%2C%20Kerala!3m2!1d9.2647582!2d76.78704139999999!4m5!1s0x3b080b78cfa52adb%3A0x721386618b0fe4d!2sMar%20Thoma%20Public%20School%2C%20Ottikali%20Rd%2C%20near%20Infopark%20%26%20Smart%20City%2C%20Edachira%2C%20Kakkanad%2C%20Kerala%20682030!3m2!1d10.019109!2d76.37005979999999!5e0!3m2!1sen!2sin!4v1676096486712!5m2!1sen!2sin" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>')
        elif busID == 'B':
            pass
        elif busID == 'None':
            self.mapView.setUrl(QtCore.QUrl('about:blank'))
        else:
            pass



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    busInfo = QtWidgets.QDialog()
    ui = Ui_busInfo()
    ui.setupUi(busInfo)
    busInfo.show()
    sys.exit(app.exec_())
