# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Classes_Win.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtWebEngineWidgets


class Ui_Classes(object):
    def setupUi(self, Classes):
        Classes.setObjectName("Classes")
        Classes.resize(773, 519)
        Classes.setWindowIcon(QtGui.QIcon('Icons/classwiseTT.png')) # Attribution: <a href="https://www.flaticon.com/free-icons/semester" title="semester icons">Semester icons created by ultimatearm - Flaticon</a>

        self.classTimeTable = QtWebEngineWidgets.QWebEngineView(Classes)
        self.classTimeTable.setGeometry(QtCore.QRect(10, 50, 571, 451))
        self.classTimeTable.setUrl(QtCore.QUrl("about:blank"))
        self.classTimeTable.setObjectName("classTimeTable")
        self.label = QtWidgets.QLabel(Classes)
        self.label.setGeometry(QtCore.QRect(200, 10, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(Classes)
        self.widget.setGeometry(QtCore.QRect(590, 50, 171, 451))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(9)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.KinderGarden = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(9)
        self.KinderGarden.setFont(font)
        self.KinderGarden.setObjectName("KinderGarden")
        self.KinderGarden.clicked.connect(lambda: self.userResponse('Kinder Garden'))
        self.verticalLayout.addWidget(self.KinderGarden)
        self.Class_1 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(9)
        self.Class_1.setFont(font)
        self.Class_1.setObjectName("Class_1")
        self.Class_1.clicked.connect(lambda: self.userResponse('Class I'))
        self.verticalLayout.addWidget(self.Class_1)
        self.Class_2 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(9)
        self.Class_2.setFont(font)
        self.Class_2.setObjectName("Class_2")
        self.Class_2.clicked.connect(lambda: self.userResponse('Class II'))
        self.verticalLayout.addWidget(self.Class_2)
        self.Class_3 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(9)
        self.Class_3.setFont(font)
        self.Class_3.setObjectName("Class_3")
        self.Class_3.clicked.connect(lambda: self.userResponse('Class III'))
        self.verticalLayout.addWidget(self.Class_3)
        self.Class_4 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(9)
        self.Class_4.setFont(font)
        self.Class_4.setObjectName("Class_4")
        self.Class_4.clicked.connect(lambda: self.userResponse('Class IV'))
        self.verticalLayout.addWidget(self.Class_4)
        self.Class_5 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(9)
        self.Class_5.setFont(font)
        self.Class_5.setObjectName("Class_5")
        self.Class_5.clicked.connect(lambda: self.userResponse('Class V'))
        self.verticalLayout.addWidget(self.Class_5)
        self.Class_6 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(9)
        self.Class_6.setFont(font)
        self.Class_6.setObjectName("Class_6")
        self.Class_6.clicked.connect(lambda: self.userResponse('Class VI'))
        self.verticalLayout.addWidget(self.Class_6)
        self.Class_7 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(9)
        self.Class_7.setFont(font)
        self.Class_7.setObjectName("Class_7")
        self.Class_7.clicked.connect(lambda: self.userResponse('Class VII'))
        self.verticalLayout.addWidget(self.Class_7)
        self.Class_8 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(9)
        self.Class_8.setFont(font)
        self.Class_8.setObjectName("Class_8")
        self.Class_8.clicked.connect(lambda: self.userResponse('Class VIII'))
        self.verticalLayout.addWidget(self.Class_8)
        self.Class_9 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(9)
        self.Class_9.setFont(font)
        self.Class_9.setObjectName("Class_9")
        self.Class_9.clicked.connect(lambda: self.userResponse('Class IX'))
        self.verticalLayout.addWidget(self.Class_9)
        self.Class_10 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(9)
        self.Class_10.setFont(font)
        self.Class_10.setObjectName("Class_10")
        self.Class_10.clicked.connect(lambda: self.userResponse('Class X'))
        self.verticalLayout.addWidget(self.Class_10)
        self.Class_11 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Class_11.setFont(font)
        self.Class_11.setObjectName("Class_11")
        self.Class_11.clicked.connect(lambda: self.userResponse('Class XI'))
        self.verticalLayout.addWidget(self.Class_11)
        self.Class_12 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Class_12.setFont(font)
        self.Class_12.setObjectName("Class_12")
        self.Class_12.clicked.connect(lambda: self.userResponse('Class XII'))
        self.verticalLayout.addWidget(self.Class_12)

        self.retranslateUi(Classes)
        QtCore.QMetaObject.connectSlotsByName(Classes)

    def retranslateUi(self, Classes):
        _translate = QtCore.QCoreApplication.translate
        Classes.setWindowTitle(_translate("Classes", "Class-wise Time Table"))
        self.label.setText(_translate("Classes", "Class-wise Time Table"))
        self.KinderGarden.setText(_translate("Classes", "Kinder Garden"))
        self.Class_1.setText(_translate("Classes", "Class I"))
        self.Class_2.setText(_translate("Classes", "Class II"))
        self.Class_3.setText(_translate("Classes", "Class III"))
        self.Class_4.setText(_translate("Classes", "Class IV"))
        self.Class_5.setText(_translate("Classes", "Class V"))
        self.Class_6.setText(_translate("Classes", "Class VI"))
        self.Class_7.setText(_translate("Classes", "Class VII"))
        self.Class_8.setText(_translate("Classes", "Class VIII"))
        self.Class_9.setText(_translate("Classes", "Class IX"))
        self.Class_10.setText(_translate("Classes", "Class X"))
        self.Class_11.setText(_translate("Classes", "Class XI"))
        self.Class_12.setText(_translate("Classes", "Class XII"))

    def userResponse(self, button):
        if button == 'Kinder Garden':
            print('Kinder Garden button pressed')
            self.classTimeTable.setHtml("about:blank")
        elif button == 'Class I':
            print('Class I button pressed')
            self.classTimeTable.setHtml("about:blank")
        elif button == 'Class II':
            print('Class II button pressed')
            self.classTimeTable.setHtml("about:blank")
        elif button == 'Class III':
            print('Class III button pressed')
            self.classTimeTable.setHtml("about:blank")
        elif button == 'Class IV':
            print('Class IV button pressed')
            self.classTimeTable.setHtml("about:blank")
        elif button == 'Class V':
            print('Class V button pressed')
            self.classTimeTable.setHtml("about:blank")
        elif button == 'Class VI':
            print('Class VI button pressed')
            self.classTimeTable.setHtml("about:blank")
        elif button == 'Class VII':
            print('Class VII button pressed')
            self.classTimeTable.setHtml("about:blank")
        elif button == 'Class VIII':
            print('Class VIII button pressed')
            self.classTimeTable.setHtml("about:blank")
        elif button == 'Class IX':
            print('Class IX button pressed')
            self.classTimeTable.setHtml("about:blank")
        elif button == 'Class X':
            print('Class X button pressed')
            self.classTimeTable.setHtml("about:blank")
        elif button == 'Class XI':
            print('Class XI button pressed')
            self.classTimeTable.setHtml("about:blank")
        elif button == 'Class XII':
            print('Class XII button pressed')
            self.classTimeTable.setHtml("about:blank")
        else:
            pass





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Classes = QtWidgets.QDialog()
    ui = Ui_Classes()
    ui.setupUi(Classes)
    Classes.show()
    sys.exit(app.exec_())
