# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Curriculum_Win.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtWidgets, QtGui
from PyQt5 import QtWebEngineWidgets



class Ui_Dialog(object):
    def setupUi(self, Dialog):

        buttonFontsize=10
        Dialog.setObjectName("Dialog")
        Dialog.resize(802, 660)
        Dialog.setWindowIcon(QtGui.QIcon('Icons/curriculum_Win_icon.png')) # Attribution: <a href="https://www.flaticon.com/free-icons/course" title="course icons">Course icons created by orvipixel - Flaticon</a>
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 802, 660))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cb_view = QtWebEngineWidgets.QWebEngineView(self.widget)
        self.cb_view.setZoomFactor(1.0)
        with open('Curriculum and Book List/default.html', 'r') as f:
            html = f.read()
            self.cb_view.setHtml(str(html))
        self.cb_view.setObjectName("cb_view")

        self.verticalLayout.addWidget(self.cb_view)
        self.curriculum = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(buttonFontsize)
        self.curriculum.setFont(font)
        self.curriculum.setObjectName("curriculum")
        self.curriculum.clicked.connect(lambda: self.Curriculum_or_bookList_Info('curriculum'))
        self.verticalLayout.addWidget(self.curriculum)
        self.bookList = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(buttonFontsize)
        self.bookList.setFont(font)
        self.bookList.setObjectName("bookList")
        self.bookList.clicked.connect(lambda: self.Curriculum_or_bookList_Info('bookList'))
        self.verticalLayout.addWidget(self.bookList)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Curriculum and Book List Info"))
        self.curriculum.setText(_translate("Dialog", "Curriculum"))
        self.bookList.setText(_translate("Dialog", "Book List"))


    def Curriculum_or_bookList_Info(self, button):
        if button == 'curriculum':
            print('Curriculum pressed')
            with open('Curriculum and Book List/Curriculum_Info.html', 'r') as f:
                html = f.read()
                self.cb_view.setHtml(html)
        elif button == 'bookList':
            print('Book List pressed')
            with open('Curriculum and Book List/booklist22.html', 'r') as f:
                html = f.read()
                self.cb_view.setHtml(html)



if __name__ == "__main__":


    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
