# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pta_Win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtWebEngineWidgets


class Ui_PTA_C(object):
    def setupUi(self, PTA_C):

        PTA_C.setObjectName("PTA_C")
        PTA_C.resize(747, 583)
        self.PTA_C_viewer = QtWebEngineWidgets.QWebEngineView(PTA_C)
        self.PTA_C_viewer.setGeometry(QtCore.QRect(10, 70, 591, 501))
        with open('Curriculum and Book List/default.html', 'r') as f:
            html = f.read()
            self.PTA_C_viewer.setHtml(str(html))
        self.PTA_C_viewer.setObjectName("PTA_C_viewer")
        self.OHC = QtWidgets.QLabel(PTA_C)
        self.OHC.setGeometry(QtCore.QRect(110, 10, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(20)
        self.OHC.setFont(font)
        self.OHC.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.OHC.setScaledContents(True)
        self.OHC.setAlignment(QtCore.Qt.AlignCenter)
        self.OHC.setObjectName("OHC")
        self.widget = QtWidgets.QWidget(PTA_C)
        self.widget.setGeometry(QtCore.QRect(610, 80, 131, 491))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(16)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.openHouse = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(16)
        self.openHouse.setFont(font)
        self.openHouse.setObjectName("openHouse")
        self.openHouse.clicked.connect(lambda: self.userButtonresponse('openHouse'))
        self.verticalLayout.addWidget(self.openHouse)
        self.circulars = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(16)
        self.circulars.setFont(font)
        self.circulars.setObjectName("circulars")
        self.circulars.clicked.connect(lambda: self.userButtonresponse('circulars'))
        self.verticalLayout.addWidget(self.circulars)

        self.retranslateUi(PTA_C)
        QtCore.QMetaObject.connectSlotsByName(PTA_C)

    def retranslateUi(self, PTA_C):
        _translate = QtCore.QCoreApplication.translate
        PTA_C.setWindowTitle(_translate("PTA_C", "Dialog"))
        self.OHC.setText(_translate("PTA_C", "Open House/Circulars"))
        self.openHouse.setText(_translate("PTA_C", " Open House"))
        self.circulars.setText(_translate("PTA_C", "Circulars"))

    def userButtonresponse(self, button):
        if button == 'openHouse':
            print("Open House pressed")
            with open('Circulars_PTA/PTA.html', 'r') as f:
                html = f.read()
                self.PTA_C_viewer.setHtml(str(html))
        elif button == 'circulars':
            print("Circulars pressed")
            with open('Circulars_PTA/CIRCULARS.html', 'r') as f:
                html = f.read()
                self.PTA_C_viewer.setHtml(str(html))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PTA_C = QtWidgets.QDialog()
    ui = Ui_PTA_C()
    ui.setupUi(PTA_C)
    PTA_C.show()
    sys.exit(app.exec_())
